### ISSUE TITLE
Invalid Prop Type Warning for placement in Badge Component

### ISSUE THREAD

**Issue by dstoneva** [creativetimofficial/material-tailwind#429]
When using the Badge component from @material-tailwind/react, an invalid prop type warning appears in the console. The warning specifically mentions that the placement prop type should be a function, but it receives an object.

Steps to Reproduce:

1. Import and use the Badge component from @material-tailwind/react.
2. Set the placement prop to one of the valid values, e.g., "top-end".
3. Check the console when running the application in development mode.

Expected Behavior:
There should be no prop type warning when using the Badge component with a valid placement value.

Actual Behavior:
A console warning is displayed:
Warning: Failed prop type: MaterialTailwind.Badge: prop type `placement` is invalid; it must be a function, usually from the `prop-types` package, but received `object`. This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.

Environment:

Library Version: material-tailwind/react: 2.1.0
React Version: 18.2.0,
Browser: Chrome 115.0.5790.171 (Official Build) (64-bit)
OS: Windows 10 Pro

**Comment by szprytny** [comment]
I can see the same error in console for 2 props: `overlap` and `placement`

**Comment by guotingchao** [comment]
+1, I have same issue

**Comment by rominabocon** [comment]
Same issue!!

**Comment by jeansy42** [comment]
I have same issue too

**Comment by alexmady** [comment]
+1

**Comment by RenaldiPranata** [comment]
+1, I have same issue

**Comment by scobbe** [comment]
+1

**Comment by khsuzan** [comment]
any solution?

**Comment by sajadevo** [comment]
This issue is fixed on v2.1.2

**Comment by rominabocon** [comment]
Actually is not. 
![image](https://github.com/creativetimofficial/material-tailwind/assets/63875657/6f56bb61-bab5-4753-a268-00407d9804d2)

**Comment by URafaelRocha** [comment]
![image](https://github.com/user-attachments/assets/5598814f-320e-49f9-9820-b5a2d956d437)
It's definitely not resolved

**Comment by amiapmorais** [comment]
Same issue here, despite following the docs https://www.material-tailwind.com/docs/react/badge#types-overlap

`<Badge
          content={
            allNotifications.filter((notification) => !notification.read).length
          }
          className="scale-90"
          color="purple"
          invisible={allNotifications.length === 0}
          overlap="circular"
        >`

![Image](https://github.com/user-attachments/assets/13688196-6029-48be-ad8a-a83b75305730)
